### PR TITLE
Ensure all members are initialized.

### PR DESCRIPTION
**Pull request by lewie-donckers**
Ensure all members are initialized.

Since the members were previously uninitialized and the software seemed to work fine, the actual value of the initialized variables apparently is not important. So i just went with 0.

clang-tidy can check this. I will add a clang-tidy file once its warning have been fixed.

### CODE REVIEW

**Comment by Rayman** [comment]
Question: all these values are probably initialized, but not immediately where they are declared. Just a little bit later. Can't `clang-tidy` see further into the code to notice nothing is wrong?

**Comment by lewie-donckers** [comment]
> Question: all these values are probably initialized, but not immediately where they are declared. Just a little bit later. Can't `clang-tidy` see further into the code to notice nothing is wrong?

It warns about the members not being initialized in the constructor. Which is - to say the least - a best practice. Since the objects are not constructed very often, there are no noticeable performance penalties.

**Comment by Timple** [comment]
I'm not worried about performance. But a developer might now assume they are used.
Perhaps using `-1` and `NaN` as default will make clear that later overwrites are intended?

**Comment by lewie-donckers** [comment]
> I'm not worried about performance. But a developer might now assume they are used. Perhaps using `-1` and `NaN` as default will make clear that later overwrites are intended?

That's fine with me. But I will need some help then. Which members should get which value? (Feel free to commit required changes.)

**Comment by Timple** [comment]
All `int` a `-1` and all doubles and floats NaN.
Unfortunately, int and bool don't have NaN :)

**Comment by Rayman** [comment]
If sonarcloud can check these constructs, I would leave the code as is and remove the `clang-tidy` check. But I'm fine with changing code as well.

**Comment by lewie-donckers** [comment]
> All `int` a `-1` and all doubles and floats NaN. Unfortunately, int and bool don't have NaN :)

Fixed!

**Review by Timple — APPROVED** [review]

**Pull request merged**
