### PR TITLE
Cleaned up includes.

### PR DESCRIPTION
**Pull request by lewie-donckers**
Cleaned up includes according to the following guidelines:

- use <> for files found through include dirs and "" for files found relative to the current file see https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#sf12-prefer-the-quoted-form-of-include-for-files-relative-to-the-including-file-and-the-angle-bracket-form-everywhere-else
- regarding the order:
  - first include the corresponding header file (this one is for source files only)
  - then local files (using "")
  - then files from the same lib
  - then files from 3rd party libs (boost/ros/etc)
  - then standard includes
  - then OS includes

### CODE REVIEW

**Review by Rayman — COMMENTED** [review]
One month ago I did this PR which is in almost the opposite direction: https://github.com/nobleo/path_tracking_pid/pull/14.

There I've used a different header style (`<` vs `"`). So the question is which style do we use?

I've followed the ROS2 code style which refers to the google code style. It's not really clear but for me it boils down to:

```c++
#include "current_package/header.hpp"

#include <system_headers>

#include "other_ros_headers/header.hpp"
#include "current_package/other_header.hpp"
```
What do you think?

**Comment by lewie-donckers** [comment]
> One month ago I did this PR which is in almost the opposite direction: #14.
> 
> There I've used a different header style (`<` vs `"`). So the question is which style do we use?
> 
> I've followed the ROS2 code style which refers to the google code style. It's not really clear but for me it boils down to:
> 
> ```c++
> #include "current_package/header.hpp"
> 
> #include <system_headers>
> 
> #include "other_ros_headers/header.hpp"
> #include "current_package/other_header.hpp"
> ```
> 
> What do you think?

@Rayman the order I suggested is mostly my personal preference. The most important thing about the order is to include the corresponding header file first in every source file. Other than that - assuming the header files are correct - the order should not matter. So I'll happily use whatever guideline you guys want.

About the brackets to use ("" and <>), I recommend we do follow the standard convention which is also in the C++ Core Guidelines.

Please let me know what order you guys want to standardize in our ROS projects. @Rayman @Timple @rokusottervanger.

**Comment by Timple** [comment]
ROS1 linter doesn't care about `"` or `<`.

The ROS2 clang formatter uses `<`. So I propose to go for these?

When I'm on my work-pc I can try `ament_clang_format --reformat` and verify it's output.
_But frankly I don't mind much 🙂_

**Comment by Timple** [comment]
So I noticed the ROS2 formatter doesn't care about `<` and `"`. 

> use <> for files found through include dirs and "" for files found relative to the current file

This does seem to be the main difference between the two styles. So I propose to merge this in line with that.

@Rayman any last thoughts?

**Comment by lewie-donckers** [comment]
I just tried the ROS2 clang-format file provided by @Timple : https://github.com/ament/ament_lint/blob/master/ament_clang_format/ament_clang_format/configuration/.clang-format

And it will automatically group and sort all includes. (Using an odd order but at least it's standardized.)

Assuming we want to use that clang-format file, we just have to agree on the "" and <> brackets.

**Review by Timple — APPROVED** [review]

**Pull request merged**
